baseURL = 'https://example.org/'
theme = 'paper'
languageCode = 'pt-BR'
title = 'Advogada Carolina Helena'
author = "Caroline Helena"
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  linkedin = 'carolina-helena-gonçalves-da-silva-8885b024'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'carolhgs@gmail.com'                 # gravatar email or image url
  name = 'Carolina Helena'
  bio = 'Advogada Trabalhista e Civil (Família, Consumidor e Contratos)'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'https://cdn.v2ex.com/gravatar/'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = false                               # enable KaTeX math typesetting globally
